/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button_: typeof import('./components/button_.vue')['default']
    HexContainer: typeof import('./components/HexContainer.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    RandomText: typeof import('./components/RandomText.vue')['default']
    ResultsCard: typeof import('./components/ResultsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
